### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by john-rock** [Jozwiaczek/guitar-book#4]
Using this starter - https://github.com/gatsbyjs/gatsby-starter-hello-world

Followed the directions to setup this theme and no matter how I configure it, using the sample data or the template provided, "gatsby develop" produces the error below every time and crashes.

**Error: Cannot find module '../node_modules/gatsby-theme-guitar-book/src/assets/icon.png'**

**Comment by Jozwiaczek** [comment]
@john-rock probably using[ this starter](https://github.com/gatsbyjs/gatsby-starter-hello-world) is not the best the way to start with guitar-book plugin. If you copy the [template directory](https://github.com/Jozwiaczek/guitar-book/tree/master/apps/template) and open it as a separate project it should work. The [template directory](https://github.com/Jozwiaczek/guitar-book/tree/master/apps/template) is kind of starter so it doesn't require any other setup or starters.

**Comment by Jozwiaczek** [comment]
@john-rock I fixed this error, so with gatsby-theme-guitar-book, version `1.0.1-alpha.11` it should work.
I also add [repo with just simple starter](https://github.com/Jozwiaczek/gatsby-starter-guitar-book) (it is same as it is in template directory but easier to start).

**Comment by john-rock** [comment]
@Jozwiaczek Awesome thank you I will check this out later. 

Great idea too, looking forward to future releases.
